import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
countries = pd.read_excel('imva.xlsx')
print(countries.columns)
countries = countries.drop(countries.columns[1:3], axis = 1)
print(countries.columns)
countries = countries.drop(countries.columns[30: ], axis = 1)
print(countries.columns)
countries = countries.drop(countries.filter(like = 'Asia'), axis = 1)
print(countries.columns)
countries = countries.drop(countries.filter(like = 'Greater'), axis = 1)
print(countries.columns)
country = countries['Variables'].str.split(' ', n = 1, expand = True)
print(country)
countries = countries.assign(Year = country[0])
countries = countries.assign(Month = country[1])
print(countries)
countries['Year'] = pd.to_numeric(countries['Year'])
countries = countries[(countries['Year'] >= 1998) & (countries['Year'] <= 2007)]
print(countries)
countries = countries.apply(pd.to_numeric, errors = 'coerce').fillna(0)
countries = countries[['Brunei Darussalam', 'Indonesia', 'Malaysia', 'Myanmar', 'Philippines', 'Thailand', 'Vietnam', 'China', 'Hong Kong SAR', 'Taiwan', 'Japan', 'South Korea', 'Bangladesh', 'India', 'Pakistan', 'Sri Lanka', 'Iran', 'Israel', 'Kuwait', 'Saudi Arabia', 'United Arab Emirates']]
ps = countries.sum().sort_values()
print(ps.index)
index = np.arange(len(ps.index))
plt.xlabel('Countries', fontsize = 10)
plt.ylabel('Number of Visitors', fontsize = 10)
plt.xticks(index, ps.index, fontsize = 10, rotation = 90)
plt.title('Number of Visitors from Countries')
plt.scatter(ps.index, ps.values / 1000)
plt.show()
ps2 = ps.nlargest(3)
print(ps2)
index = np.arange(len(ps2.index))
plt.xlabel('Top 3 Countries', fontsize = 10)
plt.ylabel('Number of Visitors', fontsize = 10)
plt.xticks(index, ps2.index, fontsize = 10, rotation = 90)
plt.title('Number of Vistors from Top 3 Countries')
plt.bar(ps2.index, ps2.values / 1000)
plt.show()